/**
 * Canonical FDA non-device CDS footer required on every ARKA-INS CDS card `detail` field.
 * Keep in sync with `.cursorrules` and go-live grep tests.
 */

/** Version string recorded in decision logs and regulatory exports. */
export const FDA_DISCLOSURE_VERSION = '1.1.0';

export const FDA_NON_DEVICE_CDS_DISCLOSURE =
  "This recommendation is intended to support, not replace, clinical judgment. It is generated by ARKA, software designed to meet the four criteria for Non-Device Clinical Decision Support under FD&C Act §520(o)(1)(E) and FDA's 2022 final guidance on Clinical Decision Support Software. The clinician is responsible for the final decision.";

/**
 * Substrings used by CDS sandbox harness and CI grep tests (detail may use markdown emphasis).
 */
export const FDA_DISCLOSURE_MARKERS = [
  "Non-Device Clinical Decision Support",
  "FD&C Act",
  "clinician is responsible for the final decision",
] as const;

/**
 * Returns true when `detail` includes the canonical disclosure (markdown-tolerant).
 *
 * @param detail - CDS card detail markdown.
 */
export function detailIncludesFdaDisclosure(detail: string | undefined): boolean {
  if (!detail?.trim()) {
    return false;
  }
  const normalized = detail.replace(/\*/g, "");
  return normalized.includes(FDA_NON_DEVICE_CDS_DISCLOSURE);
}
