import type { FacilityProfile } from "./types";

/**
 * Mock facility profiles for demos. Each represents a realistic
 * rural facility archetype that maps to the playbook personas.
 */

export const DEMO_FACILITIES: FacilityProfile[] = [
  // ---- FACILITY 1: Critical Access Hospital in Kansas ----
  {
    id: "fac-001",
    name: "Prairie View Community Hospital",
    type: "critical-access-hospital",
    designation: ["CAH", "HPSA", "MUA"],
    location: {
      address: "420 N Main St",
      city: "Smith Center",
      state: "KS",
      zipCode: "66967",
      county: "Smith County",
      latitude: 39.7789,
      longitude: -98.7856,
      ruralUrbanCode: 10,
      nearestUrbanCenter: "Salina, KS",
      distanceToUrbanCenter: 95,
      population: 4800,
    },
    equipment: [
      {
        id: "eq-001",
        modality: "X-ray",
        manufacturer: "GE Healthcare",
        model: "Optima XR220amx",
        yearInstalled: 2015,
        age: 11,
        capabilities: ["Digital radiography", "Portable"],
        limitations: ["No tomosynthesis"],
        doseReductionCapable: true,
        aiCompatible: false,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2026-01-15",
        nextMaintenanceDate: "2026-07-15",
        utilizationRate: 65,
        averageStudiesPerDay: 8,
      },
      {
        id: "eq-002",
        modality: "Ultrasound",
        manufacturer: "Philips",
        model: "EPIQ 7",
        yearInstalled: 2019,
        age: 7,
        capabilities: ["General", "OB/GYN", "Vascular", "MSK", "POCUS-capable"],
        limitations: ["No contrast-enhanced ultrasound"],
        doseReductionCapable: true, // N/A for US but true for compatibility
        aiCompatible: true,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2026-02-01",
        nextMaintenanceDate: "2026-08-01",
        utilizationRate: 45,
        averageStudiesPerDay: 4,
      },
      {
        id: "eq-003",
        modality: "C-arm",
        manufacturer: "Siemens",
        model: "Cios Fit",
        yearInstalled: 2017,
        age: 9,
        capabilities: ["Fluoroscopy", "Orthopedic procedures"],
        limitations: ["No 3D capability"],
        doseReductionCapable: true,
        aiCompatible: false,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2025-11-20",
        nextMaintenanceDate: "2026-05-20",
        utilizationRate: 20,
        averageStudiesPerDay: 1,
      },
    ],
    staffing: {
      radiologists: [],
      technologists: [
        {
          id: "staff-001",
          name: "Sarah Mitchell, RT(R)(CT)",
          role: "technologist",
          certifications: ["ARRT-R", "ARRT-CT", "BLS"],
          modalityCompetencies: ["X-ray", "CT", "C-arm"],
          fullTime: true,
          scheduledHours: 40,
        },
        {
          id: "staff-002",
          name: "Tom Hernandez, RT(R)(S)",
          role: "technologist",
          certifications: ["ARRT-R", "ARRT-S", "BLS"],
          modalityCompetencies: ["X-ray", "Ultrasound"],
          fullTime: false,
          scheduledHours: 24,
        },
      ],
      coverageSchedule: {
        weekday: { start: "07:00", end: "17:00" },
        weekend: { start: "08:00", end: "12:00" },
        holidays: "reduced",
      },
      hasAfterHoursCoverage: false,
      teleradiologyForAfterHours: true,
    },
    mobileUnits: [
      {
        id: "mu-001",
        modality: "CT",
        provider: "Shared Medical Services",
        visitDays: ["Tuesday", "Thursday"],
        visitFrequency: "weekly",
        nextVisitDate: "2026-04-01",
        slotsPerVisit: 12,
        averageUtilization: 75,
        contactPhone: "(800) 555-0101",
        schedulingUrl: "https://example.com/schedule",
      },
      {
        id: "mu-002",
        modality: "MRI",
        provider: "RAYUS Radiology",
        visitDays: ["Wednesday"],
        visitFrequency: "biweekly",
        nextVisitDate: "2026-04-03",
        slotsPerVisit: 8,
        averageUtilization: 60,
        contactPhone: "(800) 555-0102",
      },
    ],
    teleradiologyProviders: [
      {
        id: "tele-001",
        name: "NightHawk Radiology",
        servicesProvided: ["general-reads", "emergency-stat"],
        averageTurnaroundMinutes: 35,
        subspecialties: ["General Diagnostic"],
        costPerRead: 45,
        contractStatus: "active",
        qualityScore: 88,
        availableHours: "after-hours-only",
      },
      {
        id: "tele-002",
        name: "Virtual Radiologic",
        servicesProvided: ["general-reads", "subspecialty-neuro", "subspecialty-msk", "ai-triage"],
        averageTurnaroundMinutes: 25,
        subspecialties: ["Neuroradiology", "Musculoskeletal", "Body"],
        costPerRead: 65,
        contractStatus: "active",
        qualityScore: 94,
        availableHours: "24/7",
      },
    ],
    transferAgreements: [
      {
        id: "xfer-001",
        partnerFacilityId: "fac-hub-001",
        partnerFacilityName: "Salina Regional Health Center",
        distanceMiles: 95,
        estimatedTransferMinutes: 90,
        availableModalities: ["CT", "CT-with-contrast", "MRI", "MRI-with-contrast", "Nuclear-Medicine", "PET-CT"],
        transferProtocol: "ambulance",
        preNotificationRequired: true,
        contactPhone: "(785) 452-7000",
        faxNumber: "(785) 452-7001",
        acceptsDirectScheduling: true,
      },
    ],
    financials: {
      annualImagingRevenue: 820000,
      operatingMarginPercent: -2.1,
      payerMix: [
        { payer: "Medicare", percentVolume: 52, averageReimbursementRate: 0.78, denialRate: 8 },
        { payer: "Medicaid", percentVolume: 18, averageReimbursementRate: 0.45, denialRate: 15 },
        { payer: "Commercial", percentVolume: 22, averageReimbursementRate: 1.0, denialRate: 12 },
        { payer: "Uninsured", percentVolume: 8, averageReimbursementRate: 0.15, denialRate: 0 },
      ],
      atRiskOfClosure: true,
      riskScore: 72,
    },
    networkRole: "spoke",
    hubFacilityId: "fac-hub-001",
    operationalStatus: "active",
    lastUpdated: "2026-03-15",
  },

  // ---- FACILITY 2: Rural Emergency Hospital (REH) in Oklahoma ----
  {
    id: "fac-002",
    name: "Cimarron County REH",
    type: "rural-emergency-hospital",
    designation: ["REH", "HPSA"],
    location: {
      address: "100 Hospital Dr",
      city: "Boise City",
      state: "OK",
      zipCode: "73933",
      county: "Cimarron County",
      latitude: 36.7297,
      longitude: -102.5133,
      ruralUrbanCode: 10,
      nearestUrbanCenter: "Amarillo, TX",
      distanceToUrbanCenter: 130,
      population: 2100,
    },
    equipment: [
      {
        id: "eq-004",
        modality: "X-ray",
        manufacturer: "Canon Medical",
        model: "CXDI-710C Wireless",
        yearInstalled: 2022,
        age: 4,
        capabilities: ["Digital radiography", "Portable", "DR wireless"],
        limitations: [],
        doseReductionCapable: true,
        aiCompatible: true,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2026-02-28",
        nextMaintenanceDate: "2026-08-28",
        utilizationRate: 55,
        averageStudiesPerDay: 6,
      },
      {
        id: "eq-005",
        modality: "Ultrasound",
        manufacturer: "Butterfly Network",
        model: "Butterfly iQ+",
        yearInstalled: 2024,
        age: 2,
        capabilities: ["POCUS", "FAST", "Cardiac", "Lung", "Soft tissue"],
        limitations: ["Handheld only — not suitable for detailed vascular or OB studies"],
        doseReductionCapable: true,
        aiCompatible: true,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2026-01-10",
        nextMaintenanceDate: "2026-07-10",
        utilizationRate: 30,
        averageStudiesPerDay: 3,
      },
    ],
    staffing: {
      radiologists: [],
      technologists: [
        {
          id: "staff-003",
          name: "James Crow, RT(R)",
          role: "technologist",
          certifications: ["ARRT-R", "BLS", "ACLS"],
          modalityCompetencies: ["X-ray", "C-arm"],
          fullTime: true,
          scheduledHours: 40,
        },
      ],
      coverageSchedule: {
        weekday: { start: "07:00", end: "19:00" },
        weekend: { start: "08:00", end: "16:00" },
        holidays: "normal",
      },
      hasAfterHoursCoverage: false,
      teleradiologyForAfterHours: true,
    },
    mobileUnits: [
      {
        id: "mu-003",
        modality: "CT",
        provider: "Shared Medical Services",
        visitDays: ["Monday"],
        visitFrequency: "biweekly",
        nextVisitDate: "2026-04-07",
        slotsPerVisit: 10,
        averageUtilization: 50,
        contactPhone: "(800) 555-0103",
      },
    ],
    teleradiologyProviders: [
      {
        id: "tele-003",
        name: "Radiology Partners",
        servicesProvided: ["general-reads", "emergency-stat", "ai-triage"],
        averageTurnaroundMinutes: 20,
        subspecialties: ["General Diagnostic", "Emergency"],
        costPerRead: 55,
        contractStatus: "active",
        qualityScore: 91,
        availableHours: "24/7",
      },
    ],
    transferAgreements: [
      {
        id: "xfer-002",
        partnerFacilityId: "fac-hub-002",
        partnerFacilityName: "Northwest Texas Healthcare System",
        distanceMiles: 130,
        estimatedTransferMinutes: 120,
        availableModalities: ["CT", "CT-with-contrast", "MRI", "MRI-with-contrast", "Nuclear-Medicine", "PET-CT"],
        transferProtocol: "ambulance",
        preNotificationRequired: true,
        contactPhone: "(806) 354-1000",
        acceptsDirectScheduling: false,
      },
    ],
    financials: {
      annualImagingRevenue: 380000,
      operatingMarginPercent: 1.8,
      payerMix: [
        { payer: "Medicare", percentVolume: 60, averageReimbursementRate: 0.82, denialRate: 6 },
        { payer: "Medicaid", percentVolume: 15, averageReimbursementRate: 0.42, denialRate: 18 },
        { payer: "Commercial", percentVolume: 18, averageReimbursementRate: 1.0, denialRate: 10 },
        { payer: "Uninsured", percentVolume: 7, averageReimbursementRate: 0.10, denialRate: 0 },
      ],
      monthlyREHPayment: 285625.9,
      atRiskOfClosure: false,
      riskScore: 35,
    },
    networkRole: "independent",
    operationalStatus: "active",
    lastUpdated: "2026-03-10",
  },

  // ---- FACILITY 3: Regional Hub Hospital ----
  {
    id: "fac-hub-001",
    name: "Salina Regional Health Center",
    type: "regional-medical-center",
    designation: [],
    location: {
      address: "400 S Santa Fe Ave",
      city: "Salina",
      state: "KS",
      zipCode: "67401",
      county: "Saline County",
      latitude: 38.8403,
      longitude: -97.6114,
      ruralUrbanCode: 4,
      nearestUrbanCenter: "Wichita, KS",
      distanceToUrbanCenter: 90,
      population: 47000,
    },
    equipment: [
      {
        id: "eq-010",
        modality: "CT",
        manufacturer: "Siemens Healthineers",
        model: "SOMATOM Force",
        yearInstalled: 2023,
        age: 3,
        capabilities: ["Dual-source", "Ultra-low dose", "Spectral imaging", "AI-ready", "Cardiac CT"],
        limitations: [],
        doseReductionCapable: true,
        aiCompatible: true,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2026-03-01",
        nextMaintenanceDate: "2026-09-01",
        utilizationRate: 82,
        averageStudiesPerDay: 35,
      },
      {
        id: "eq-011",
        modality: "MRI",
        manufacturer: "GE Healthcare",
        model: "SIGNA Premier 3.0T",
        yearInstalled: 2022,
        age: 4,
        capabilities: ["3T", "Neuro", "MSK", "Cardiac", "Spectroscopy", "AI-ready"],
        limitations: [],
        doseReductionCapable: true,
        aiCompatible: true,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2026-02-15",
        nextMaintenanceDate: "2026-08-15",
        utilizationRate: 78,
        averageStudiesPerDay: 22,
      },
      {
        id: "eq-012",
        modality: "PET-CT",
        manufacturer: "Siemens Healthineers",
        model: "Biograph Vision",
        yearInstalled: 2024,
        age: 2,
        capabilities: ["Silicon photomultiplier", "Ultra-high resolution", "AI-ready"],
        limitations: [],
        doseReductionCapable: true,
        aiCompatible: true,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2026-01-20",
        nextMaintenanceDate: "2026-07-20",
        utilizationRate: 60,
        averageStudiesPerDay: 8,
      },
      {
        id: "eq-013",
        modality: "X-ray",
        manufacturer: "Canon Medical",
        model: "CXDI-810C Wireless",
        yearInstalled: 2023,
        age: 3,
        capabilities: ["Digital radiography", "AI-integrated"],
        limitations: [],
        doseReductionCapable: true,
        aiCompatible: true,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2026-03-05",
        nextMaintenanceDate: "2026-09-05",
        utilizationRate: 70,
        averageStudiesPerDay: 45,
      },
      {
        id: "eq-014",
        modality: "Ultrasound",
        manufacturer: "Philips",
        model: "EPIQ Elite",
        yearInstalled: 2024,
        age: 2,
        capabilities: ["General", "OB/GYN", "Vascular", "MSK", "Cardiac", "CEUS"],
        limitations: [],
        doseReductionCapable: true,
        aiCompatible: true,
        maintenanceStatus: "operational",
        lastMaintenanceDate: "2026-02-20",
        nextMaintenanceDate: "2026-08-20",
        utilizationRate: 65,
        averageStudiesPerDay: 18,
      },
    ],
    staffing: {
      radiologists: [
        {
          id: "staff-010",
          name: "Dr. Karen Liu, MD",
          role: "radiologist",
          certifications: ["ABR-DR", "ABR-NR", "ACR Fellow"],
          modalityCompetencies: ["CT", "MRI", "X-ray", "Ultrasound", "Nuclear-Medicine", "PET-CT"],
          fullTime: true,
          scheduledHours: 45,
        },
        {
          id: "staff-011",
          name: "Dr. Robert Tanaka, MD",
          role: "radiologist",
          certifications: ["ABR-DR", "ABR-MSK"],
          modalityCompetencies: ["CT", "MRI", "X-ray", "Ultrasound"],
          fullTime: true,
          scheduledHours: 40,
        },
      ],
      technologists: [
        {
          id: "staff-012",
          name: "Angela Davis, RT(R)(CT)(MR)",
          role: "technologist",
          certifications: ["ARRT-R", "ARRT-CT", "ARRT-MR"],
          modalityCompetencies: ["X-ray", "CT", "MRI"],
          fullTime: true,
          scheduledHours: 40,
        },
        {
          id: "staff-013",
          name: "Marcus Johnson, RT(R)(CT)",
          role: "technologist",
          certifications: ["ARRT-R", "ARRT-CT", "BLS"],
          modalityCompetencies: ["X-ray", "CT", "C-arm"],
          fullTime: true,
          scheduledHours: 40,
        },
        {
          id: "staff-014",
          name: "Lisa Patel, RT(R)(S)",
          role: "technologist",
          certifications: ["ARRT-R", "ARRT-S", "RDMS"],
          modalityCompetencies: ["X-ray", "Ultrasound"],
          fullTime: true,
          scheduledHours: 40,
        },
      ],
      coverageSchedule: {
        weekday: { start: "06:00", end: "22:00" },
        weekend: { start: "07:00", end: "19:00" },
        holidays: "normal",
      },
      hasAfterHoursCoverage: true,
      teleradiologyForAfterHours: false,
    },
    mobileUnits: [],
    teleradiologyProviders: [],
    transferAgreements: [],
    financials: {
      annualImagingRevenue: 12500000,
      operatingMarginPercent: 4.2,
      payerMix: [
        { payer: "Medicare", percentVolume: 38, averageReimbursementRate: 0.85, denialRate: 5 },
        { payer: "Medicaid", percentVolume: 12, averageReimbursementRate: 0.5, denialRate: 10 },
        { payer: "Commercial", percentVolume: 42, averageReimbursementRate: 1.0, denialRate: 8 },
        { payer: "Uninsured", percentVolume: 8, averageReimbursementRate: 0.2, denialRate: 0 },
      ],
      atRiskOfClosure: false,
      riskScore: 12,
    },
    networkRole: "hub",
    operationalStatus: "active",
    lastUpdated: "2026-03-18",
  },
];

export const mockFacilities = DEMO_FACILITIES;

export const getDemoFacility = (id: string): FacilityProfile | undefined =>
  DEMO_FACILITIES.find((f) => f.id === id);

export const getDemoFacilitiesByRole = (role: "hub" | "spoke" | "independent"): FacilityProfile[] =>
  DEMO_FACILITIES.filter((f) => f.networkRole === role);

export function getFacilityById(id: string): FacilityProfile | undefined {
  return getDemoFacility(id);
}

export function facilityHasMri(f: FacilityProfile): boolean {
  return f.equipment.some((e) => e.modality === "MRI" || e.modality === "MRI-with-contrast");
}

export function facilityCtSliceCount(f: FacilityProfile): number | null {
  const ct = f.equipment.find((e) => e.modality === "CT" || e.modality === "CT-with-contrast");
  if (!ct) return null;
  const blob = `${ct.model} ${ct.capabilities.join(" ")}`;
  const m = /(\d+)\s*-?\s*slice/i.exec(blob);
  return m ? parseInt(m[1]!, 10) : null;
}

export function radiologistFteEstimate(f: FacilityProfile): number {
  return f.staffing.radiologists.reduce((acc, r) => acc + (r.fullTime ? 1 : r.scheduledHours / 40), 0);
}

export function nearestHubTransferMinutes(f: FacilityProfile): number {
  const t = f.transferAgreements[0];
  return t ? t.estimatedTransferMinutes : 90;
}
