/**
 * Seeds `ins_shoppable_sites` with ~50 metro imaging rows for ARKA-INS shoppable APIs.
 *
 * Run (from repo root, with Supabase service role in env):
 *   npx tsx scripts/seed-shoppable-sites.ts
 *
 * Data sources — methodology and public references (figures are illustrative planning estimates):
 * ----------------------------------------------------------------------------------------------
 * 1) Green Imaging (https://www.greenimaging.net/) — national cash-pay MRI/CT self-pay pricing
 *    published for consumers; used as a lower bound for freestanding/imaging-center cash rows.
 * 2) RadiologyAssist (https://www.radiologyassist.com/) — self-pay imaging marketplace-style
 *    pricing bands by modality; used to cross-check cash price tiers by metro.
 * 3) CMS Hospital Price Transparency regulation & machine-readable files (45 CFR 180;
 *    https://www.cms.gov/hospital-price-transparency) — hospital gross charge and payer-specific
 *    negotiated rate *patterns* as anchors for `negotiated_rate` on hospital outpatient imaging rows.
 * 4) Turquoise Health / other transparency aggregators (public dashboards) — secondary benchmarks
 *    for allowed amount vs cash spread by market (not copied verbatim; rounded for demo seeding).
 *
 * No patient data is stored. Replace seed values with your health-system contracts for production.
 */

import { createClient } from "@supabase/supabase-js";

type SiteType = "hospital" | "imaging_center" | "freestanding" | "cash_pay";

interface SeedRow {
  id: string;
  name: string;
  address: string;
  site_type: SiteType;
  cpt_code: string;
  cash_price: number;
  negotiated_rate: number;
  in_network_payers: string[];
  quality_score: number;
  avg_wait_days: number;
  lat: number;
  lng: number;
}

/** Deterministic UUIDs (version/variant bits set) for idempotent upserts. */
function idAt(n: number): string {
  const tail = n.toString(16).padStart(12, "0");
  return `00000000-0000-4000-8000-${tail}`;
}

const PAYERS = {
  aetna: "aetna",
  uhc: "uhc",
  bcbs: "bcbs",
  cigna: "cigna",
  anthem: "anthem",
  humana: "humana",
} as const;

const rows: SeedRow[] = [
  // Kansas City — cash/imaging-center benchmarks informed by Green Imaging / RadiologyAssist self-pay MRI tiers.
  {
    id: idAt(1),
    name: "KC Imaging Pavilion",
    address: "2340 Gillham Rd, Kansas City, MO 64108",
    site_type: "imaging_center",
    cpt_code: "70553",
    cash_price: 575,
    negotiated_rate: 1890,
    in_network_payers: [PAYERS.aetna, PAYERS.uhc, PAYERS.bcbs],
    quality_score: 4.6,
    avg_wait_days: 4,
    lat: 39.0997,
    lng: -94.5786,
  },
  {
    id: idAt(2),
    name: "Truman Medical Imaging Center",
    address: "2301 Holmes St, Kansas City, MO 64108",
    site_type: "hospital",
    cpt_code: "70553",
    cash_price: 2425,
    negotiated_rate: 2100,
    in_network_payers: [PAYERS.aetna, PAYERS.anthem, PAYERS.cigna],
    quality_score: 4.1,
    avg_wait_days: 9,
    lat: 39.0857,
    lng: -94.5756,
  },
  {
    id: idAt(3),
    name: "Northland Radiology Associates",
    address: "5330 N Oak Trafficway, Kansas City, MO 64118",
    site_type: "freestanding",
    cpt_code: "70553",
    cash_price: 625,
    negotiated_rate: 1750,
    in_network_payers: [PAYERS.bcbs, PAYERS.uhc],
    quality_score: 4.4,
    avg_wait_days: 5,
    lat: 39.1512,
    lng: -94.5765,
  },
  {
    id: idAt(4),
    name: "Prairie View Open MRI",
    address: "4400 Broadway Blvd, Kansas City, MO 64111",
    site_type: "imaging_center",
    cpt_code: "73721",
    cash_price: 425,
    negotiated_rate: 1325,
    in_network_payers: [PAYERS.aetna, PAYERS.cigna],
    quality_score: 4.5,
    avg_wait_days: 3,
    lat: 39.0519,
    lng: -94.5939,
  },
  {
    id: idAt(5),
    name: "Shawnee Mission Radiology",
    address: "7450 Kessler St, Shawnee Mission, KS 66204",
    site_type: "imaging_center",
    cpt_code: "73721",
    cash_price: 399,
    negotiated_rate: 1285,
    in_network_payers: [PAYERS.uhc, PAYERS.bcbs],
    quality_score: 4.7,
    avg_wait_days: 2,
    lat: 39.0094,
    lng: -94.6706,
  },
  {
    id: idAt(6),
    name: "AdventHealth Imaging Center",
    address: "1000 E 104th St, Kansas City, MO 64131",
    site_type: "hospital",
    cpt_code: "74176",
    cash_price: 985,
    negotiated_rate: 1425,
    in_network_payers: [PAYERS.humana, PAYERS.anthem],
    quality_score: 4.0,
    avg_wait_days: 7,
    lat: 38.9856,
    lng: -94.5964,
  },
  {
    id: idAt(7),
    name: "Blue River Imaging",
    address: "4321 Wornall Rd, Kansas City, MO 64111",
    site_type: "imaging_center",
    cpt_code: "74176",
    cash_price: 495,
    negotiated_rate: 1385,
    in_network_payers: [PAYERS.aetna, PAYERS.uhc],
    quality_score: 4.5,
    avg_wait_days: 4,
    lat: 39.0344,
    lng: -94.6058,
  },
  {
    id: idAt(8),
    name: "CashPay MRI KC",
    address: "7900 W 135th St, Overland Park, KS 66223",
    site_type: "cash_pay",
    cpt_code: "70553",
    cash_price: 549,
    negotiated_rate: 1650,
    in_network_payers: [],
    quality_score: 4.2,
    avg_wait_days: 6,
    lat: 38.8838,
    lng: -94.6868,
  },
  {
    id: idAt(9),
    name: "South KC Radiology",
    address: "6601 Rockhill Rd, Kansas City, MO 64131",
    site_type: "freestanding",
    cpt_code: "74176",
    cash_price: 525,
    negotiated_rate: 1295,
    in_network_payers: [PAYERS.cigna, PAYERS.bcbs],
    quality_score: 4.3,
    avg_wait_days: 5,
    lat: 38.9631,
    lng: -94.605,
  },
  {
    id: idAt(10),
    name: "Metro Orthopedic Imaging",
    address: "3651 College Blvd, Overland Park, KS 66211",
    site_type: "imaging_center",
    cpt_code: "73721",
    cash_price: 379,
    negotiated_rate: 1195,
    in_network_payers: [PAYERS.uhc, PAYERS.aetna],
    quality_score: 4.6,
    avg_wait_days: 3,
    lat: 38.9272,
    lng: -94.6489,
  },

  // Dallas–Fort Worth — hospital anchors from CMS HPT-style negotiated rate spreads vs cash.
  {
    id: idAt(11),
    name: "Baylor Scott & White Imaging",
    address: "3500 Gaston Ave, Dallas, TX 75246",
    site_type: "hospital",
    cpt_code: "70553",
    cash_price: 2650,
    negotiated_rate: 2285,
    in_network_payers: [PAYERS.aetna, PAYERS.bcbs, PAYERS.uhc],
    quality_score: 4.2,
    avg_wait_days: 11,
    lat: 32.7867,
    lng: -96.783,
  },
  {
    id: idAt(12),
    name: "Envision Imaging Dallas",
    address: "3000 Blackburn St, Dallas, TX 75204",
    site_type: "imaging_center",
    cpt_code: "70553",
    cash_price: 595,
    negotiated_rate: 1825,
    in_network_payers: [PAYERS.cigna, PAYERS.anthem],
    quality_score: 4.6,
    avg_wait_days: 4,
    lat: 32.7935,
    lng: -96.7664,
  },
  {
    id: idAt(13),
    name: "Southwest MRI Center",
    address: "7777 Forest Ln, Dallas, TX 75230",
    site_type: "imaging_center",
    cpt_code: "70553",
    cash_price: 549,
    negotiated_rate: 1765,
    in_network_payers: [PAYERS.uhc, PAYERS.aetna],
    quality_score: 4.5,
    avg_wait_days: 3,
    lat: 32.9126,
    lng: -96.7698,
  },
  {
    id: idAt(14),
    name: "Fort Worth Imaging Pavilion",
    address: "1300 W Rosedale St, Fort Worth, TX 76104",
    site_type: "freestanding",
    cpt_code: "73721",
    cash_price: 415,
    negotiated_rate: 1245,
    in_network_payers: [PAYERS.bcbs, PAYERS.humana],
    quality_score: 4.4,
    avg_wait_days: 4,
    lat: 32.7555,
    lng: -97.3308,
  },
  {
    id: idAt(15),
    name: "Tarrant County Radiology",
    address: "1600 College Ave, Fort Worth, TX 76104",
    site_type: "hospital",
    cpt_code: "73721",
    cash_price: 1185,
    negotiated_rate: 1395,
    in_network_payers: [PAYERS.anthem, PAYERS.cigna],
    quality_score: 4.0,
    avg_wait_days: 8,
    lat: 32.745,
    lng: -97.345,
  },
  {
    id: idAt(16),
    name: "Uptown CT & MRI",
    address: "2909 Cole Ave, Dallas, TX 75204",
    site_type: "imaging_center",
    cpt_code: "74176",
    cash_price: 465,
    negotiated_rate: 1325,
    in_network_payers: [PAYERS.aetna, PAYERS.uhc],
    quality_score: 4.5,
    avg_wait_days: 3,
    lat: 32.809,
    lng: -96.801,
  },
  {
    id: idAt(17),
    name: "Medical City Dallas Imaging",
    address: "7777 Forest Ln, Dallas, TX 75230",
    site_type: "hospital",
    cpt_code: "74176",
    cash_price: 1425,
    negotiated_rate: 1585,
    in_network_payers: [PAYERS.uhc, PAYERS.bcbs],
    quality_score: 4.1,
    avg_wait_days: 6,
    lat: 32.9126,
    lng: -96.7698,
  },
  {
    id: idAt(18),
    name: "Radiology Associates of North Texas",
    address: "1300 S University Dr, Fort Worth, TX 76107",
    site_type: "imaging_center",
    cpt_code: "74176",
    cash_price: 499,
    negotiated_rate: 1285,
    in_network_payers: [PAYERS.cigna, PAYERS.aetna],
    quality_score: 4.4,
    avg_wait_days: 4,
    lat: 32.7514,
    lng: -97.3878,
  },
  {
    id: idAt(19),
    name: "DFW Cash Imaging",
    address: "5201 Harry Hines Blvd, Dallas, TX 75235",
    site_type: "cash_pay",
    cpt_code: "70553",
    cash_price: 525,
    negotiated_rate: 1595,
    in_network_payers: [],
    quality_score: 4.0,
    avg_wait_days: 5,
    lat: 32.8212,
    lng: -96.8355,
  },
  {
    id: idAt(20),
    name: "Plano Open MRI",
    address: "4000 W 15th St, Plano, TX 75093",
    site_type: "imaging_center",
    cpt_code: "73721",
    cash_price: 389,
    negotiated_rate: 1210,
    in_network_payers: [PAYERS.bcbs, PAYERS.uhc],
    quality_score: 4.6,
    avg_wait_days: 2,
    lat: 33.0198,
    lng: -96.8319,
  },

  // Phoenix — desert metro pricing; cash imaging centers vs hospital outpatient departments.
  {
    id: idAt(21),
    name: "Banner Imaging Phoenix",
    address: "1441 N 12th St, Phoenix, AZ 85006",
    site_type: "hospital",
    cpt_code: "70553",
    cash_price: 2295,
    negotiated_rate: 2150,
    in_network_payers: [PAYERS.aetna, PAYERS.anthem, PAYERS.uhc],
    quality_score: 4.2,
    avg_wait_days: 10,
    lat: 33.4656,
    lng: -112.0484,
  },
  {
    id: idAt(22),
    name: "Desert Valley MRI",
    address: "1300 N 12th St, Phoenix, AZ 85006",
    site_type: "imaging_center",
    cpt_code: "70553",
    cash_price: 579,
    negotiated_rate: 1785,
    in_network_payers: [PAYERS.cigna, PAYERS.bcbs],
    quality_score: 4.5,
    avg_wait_days: 4,
    lat: 33.4656,
    lng: -112.0484,
  },
  {
    id: idAt(23),
    name: "Scottsdale Medical Imaging",
    address: "9977 N 90th St, Scottsdale, AZ 85258",
    site_type: "imaging_center",
    cpt_code: "70553",
    cash_price: 649,
    negotiated_rate: 1895,
    in_network_payers: [PAYERS.uhc, PAYERS.aetna],
    quality_score: 4.7,
    avg_wait_days: 3,
    lat: 33.5829,
    lng: -111.896,
  },
  {
    id: idAt(24),
    name: "Valley Radiologists",
    address: "925 E McDowell Rd, Phoenix, AZ 85006",
    site_type: "freestanding",
    cpt_code: "73721",
    cash_price: 409,
    negotiated_rate: 1265,
    in_network_payers: [PAYERS.bcbs, PAYERS.humana],
    quality_score: 4.4,
    avg_wait_days: 4,
    lat: 33.4656,
    lng: -112.0484,
  },
  {
    id: idAt(25),
    name: "Arizona Diagnostic Radiology",
    address: "2929 E Camelback Rd, Phoenix, AZ 85016",
    site_type: "imaging_center",
    cpt_code: "73721",
    cash_price: 435,
    negotiated_rate: 1295,
    in_network_payers: [PAYERS.anthem, PAYERS.cigna],
    quality_score: 4.5,
    avg_wait_days: 3,
    lat: 33.5088,
    lng: -112.0829,
  },
  {
    id: idAt(26),
    name: "Phoenix General Hospital Outpatient Imaging",
    address: "1645 E Roosevelt St, Phoenix, AZ 85006",
    site_type: "hospital",
    cpt_code: "74176",
    cash_price: 1325,
    negotiated_rate: 1495,
    in_network_payers: [PAYERS.aetna, PAYERS.uhc],
    quality_score: 4.0,
    avg_wait_days: 7,
    lat: 33.4586,
    lng: -112.0345,
  },
  {
    id: idAt(27),
    name: "Camelback Imaging Center",
    address: "2020 E Rio Salado Pkwy, Tempe, AZ 85281",
    site_type: "imaging_center",
    cpt_code: "74176",
    cash_price: 479,
    negotiated_rate: 1345,
    in_network_payers: [PAYERS.bcbs, PAYERS.aetna],
    quality_score: 4.4,
    avg_wait_days: 4,
    lat: 33.4294,
    lng: -111.899,
  },
  {
    id: idAt(28),
    name: "West Valley Open MRI",
    address: "9305 W Thomas Rd, Phoenix, AZ 85037",
    site_type: "imaging_center",
    cpt_code: "70553",
    cash_price: 539,
    negotiated_rate: 1725,
    in_network_payers: [PAYERS.uhc, PAYERS.cigna],
    quality_score: 4.3,
    avg_wait_days: 5,
    lat: 33.4798,
    lng: -112.261,
  },
  {
    id: idAt(29),
    name: "Sun City Imaging",
    address: "10510 W Thunderbird Blvd, Sun City, AZ 85351",
    site_type: "freestanding",
    cpt_code: "74176",
    cash_price: 455,
    negotiated_rate: 1275,
    in_network_payers: [PAYERS.humana, PAYERS.anthem],
    quality_score: 4.2,
    avg_wait_days: 6,
    lat: 33.5975,
    lng: -112.2718,
  },
  {
    id: idAt(30),
    name: "Downtown Phoenix Cash CT",
    address: "1 N 1st St, Phoenix, AZ 85004",
    site_type: "cash_pay",
    cpt_code: "74176",
    cash_price: 425,
    negotiated_rate: 1295,
    in_network_payers: [],
    quality_score: 4.1,
    avg_wait_days: 4,
    lat: 33.4484,
    lng: -112.074,
  },

  // Atlanta — southeast hospital pricing vs freestanding MRI.
  {
    id: idAt(31),
    name: "Piedmont Imaging Midtown",
    address: "550 Peachtree St NE, Atlanta, GA 30308",
    site_type: "hospital",
    cpt_code: "70553",
    cash_price: 2485,
    negotiated_rate: 2225,
    in_network_payers: [PAYERS.aetna, PAYERS.anthem, PAYERS.bcbs],
    quality_score: 4.1,
    avg_wait_days: 9,
    lat: 33.7756,
    lng: -84.384,
  },
  {
    id: idAt(32),
    name: "Peachtree Open MRI",
    address: "1800 Peachtree St NW, Atlanta, GA 30309",
    site_type: "imaging_center",
    cpt_code: "70553",
    cash_price: 589,
    negotiated_rate: 1845,
    in_network_payers: [PAYERS.uhc, PAYERS.cigna],
    quality_score: 4.5,
    avg_wait_days: 4,
    lat: 33.8043,
    lng: -84.3893,
  },
  {
    id: idAt(33),
    name: "Northside Hospital Imaging",
    address: "1000 Johnson Ferry Rd NE, Atlanta, GA 30342",
    site_type: "hospital",
    cpt_code: "70553",
    cash_price: 2385,
    negotiated_rate: 2185,
    in_network_payers: [PAYERS.bcbs, PAYERS.aetna],
    quality_score: 4.2,
    avg_wait_days: 8,
    lat: 33.9056,
    lng: -84.3822,
  },
  {
    id: idAt(34),
    name: "Atlanta Orthopedic Imaging",
    address: "980 Howell Mill Rd NW, Atlanta, GA 30318",
    site_type: "imaging_center",
    cpt_code: "73721",
    cash_price: 419,
    negotiated_rate: 1255,
    in_network_payers: [PAYERS.anthem, PAYERS.uhc],
    quality_score: 4.4,
    avg_wait_days: 3,
    lat: 33.7897,
    lng: -84.4706,
  },
  {
    id: idAt(35),
    name: "Midtown Radiology Partners",
    address: "550 Peachtree St NE, Atlanta, GA 30308",
    site_type: "freestanding",
    cpt_code: "73721",
    cash_price: 395,
    negotiated_rate: 1195,
    in_network_payers: [PAYERS.cigna, PAYERS.bcbs],
    quality_score: 4.6,
    avg_wait_days: 2,
    lat: 33.7756,
    lng: -84.384,
  },
  {
    id: idAt(36),
    name: "Emory Outpatient Imaging",
    address: "1364 Clifton Rd NE, Atlanta, GA 30322",
    site_type: "hospital",
    cpt_code: "74176",
    cash_price: 1285,
    negotiated_rate: 1525,
    in_network_payers: [PAYERS.aetna, PAYERS.uhc],
    quality_score: 4.3,
    avg_wait_days: 6,
    lat: 33.7925,
    lng: -84.3189,
  },
  {
    id: idAt(37),
    name: "Buckhead CT & MRI",
    address: "3330 Piedmont Rd NE, Atlanta, GA 30305",
    site_type: "imaging_center",
    cpt_code: "74176",
    cash_price: 489,
    negotiated_rate: 1365,
    in_network_payers: [PAYERS.bcbs, PAYERS.anthem],
    quality_score: 4.5,
    avg_wait_days: 4,
    lat: 33.8398,
    lng: -84.3689,
  },
  {
    id: idAt(38),
    name: "Westside Imaging",
    address: "1100 West Peachtree St NW, Atlanta, GA 30309",
    site_type: "imaging_center",
    cpt_code: "74176",
    cash_price: 465,
    negotiated_rate: 1315,
    in_network_payers: [PAYERS.uhc, PAYERS.aetna],
    quality_score: 4.4,
    avg_wait_days: 3,
    lat: 33.7845,
    lng: -84.3912,
  },
  {
    id: idAt(39),
    name: "Atlanta Cash MRI",
    address: "50 Hurt Plaza SE, Atlanta, GA 30303",
    site_type: "cash_pay",
    cpt_code: "70553",
    cash_price: 559,
    negotiated_rate: 1685,
    in_network_payers: [],
    quality_score: 4.0,
    avg_wait_days: 5,
    lat: 33.749,
    lng: -84.388,
  },
  {
    id: idAt(40),
    name: "Decatur Radiology",
    address: "450 N Decatur Rd, Decatur, GA 30030",
    site_type: "imaging_center",
    cpt_code: "73721",
    cash_price: 369,
    negotiated_rate: 1185,
    in_network_payers: [PAYERS.humana, PAYERS.cigna],
    quality_score: 4.5,
    avg_wait_days: 3,
    lat: 33.792,
    lng: -84.298,
  },

  // NYC — dense hospital charges vs independent imaging (CMS HPT + cash market benchmarks).
  {
    id: idAt(41),
    name: "NYU Langone Imaging",
    address: "550 1st Ave, New York, NY 10016",
    site_type: "hospital",
    cpt_code: "70553",
    cash_price: 3250,
    negotiated_rate: 2650,
    in_network_payers: [PAYERS.aetna, PAYERS.anthem, PAYERS.uhc],
    quality_score: 4.4,
    avg_wait_days: 12,
    lat: 40.742,
    lng: -73.974,
  },
  {
    id: idAt(42),
    name: "Manhattan Open MRI",
    address: "315 Madison Ave, New York, NY 10016",
    site_type: "imaging_center",
    cpt_code: "70553",
    cash_price: 725,
    negotiated_rate: 1985,
    in_network_payers: [PAYERS.cigna, PAYERS.bcbs],
    quality_score: 4.5,
    avg_wait_days: 5,
    lat: 40.7452,
    lng: -73.9789,
  },
  {
    id: idAt(43),
    name: "Brooklyn Heights Radiology",
    address: "185 Montague St, Brooklyn, NY 11201",
    site_type: "imaging_center",
    cpt_code: "70553",
    cash_price: 649,
    negotiated_rate: 1895,
    in_network_payers: [PAYERS.uhc, PAYERS.aetna],
    quality_score: 4.3,
    avg_wait_days: 4,
    lat: 40.6945,
    lng: -73.989,
  },
  {
    id: idAt(44),
    name: "Queens Medical Imaging",
    address: "40-08 Queens Blvd, Queens, NY 11373",
    site_type: "freestanding",
    cpt_code: "73721",
    cash_price: 449,
    negotiated_rate: 1325,
    in_network_payers: [PAYERS.bcbs, PAYERS.anthem],
    quality_score: 4.4,
    avg_wait_days: 4,
    lat: 40.7365,
    lng: -73.8789,
  },
  {
    id: idAt(45),
    name: "Harlem Hospital Outpatient Radiology",
    address: "506 Lenox Ave, New York, NY 10037",
    site_type: "hospital",
    cpt_code: "73721",
    cash_price: 1385,
    negotiated_rate: 1455,
    in_network_payers: [PAYERS.aetna, PAYERS.humana],
    quality_score: 3.9,
    avg_wait_days: 10,
    lat: 40.8142,
    lng: -73.9405,
  },
  {
    id: idAt(46),
    name: "Chelsea Imaging Center",
    address: "150 W 26th St, New York, NY 10001",
    site_type: "imaging_center",
    cpt_code: "74176",
    cash_price: 525,
    negotiated_rate: 1425,
    in_network_payers: [PAYERS.uhc, PAYERS.cigna],
    quality_score: 4.5,
    avg_wait_days: 3,
    lat: 40.7484,
    lng: -73.9967,
  },
  {
    id: idAt(47),
    name: "Mount Sinai Outpatient CT",
    address: "5 E 98th St, New York, NY 10029",
    site_type: "hospital",
    cpt_code: "74176",
    cash_price: 1585,
    negotiated_rate: 1625,
    in_network_payers: [PAYERS.anthem, PAYERS.aetna],
    quality_score: 4.2,
    avg_wait_days: 7,
    lat: 40.7914,
    lng: -73.9496,
  },
  {
    id: idAt(48),
    name: "Staten Island Imaging",
    address: "256 Mason Ave, Staten Island, NY 10305",
    site_type: "imaging_center",
    cpt_code: "74176",
    cash_price: 485,
    negotiated_rate: 1295,
    in_network_payers: [PAYERS.bcbs, PAYERS.uhc],
    quality_score: 4.2,
    avg_wait_days: 5,
    lat: 40.6014,
    lng: -74.0875,
  },
  {
    id: idAt(49),
    name: "NYC Self-Pay MRI",
    address: "109 E 125th St, New York, NY 10035",
    site_type: "cash_pay",
    cpt_code: "70553",
    cash_price: 599,
    negotiated_rate: 1750,
    in_network_payers: [],
    quality_score: 4.0,
    avg_wait_days: 6,
    lat: 40.8043,
    lng: -73.9381,
  },
  {
    id: idAt(50),
    name: "Upper East Side Radiology",
    address: "115 E 61st St, New York, NY 10065",
    site_type: "imaging_center",
    cpt_code: "73721",
    cash_price: 479,
    negotiated_rate: 1345,
    in_network_payers: [PAYERS.aetna, PAYERS.anthem, PAYERS.cigna],
    quality_score: 4.6,
    avg_wait_days: 3,
    lat: 40.7624,
    lng: -73.966,
  },
];

async function main(): Promise<void> {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error("Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.");
    process.exit(1);
  }

  const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });

  const payload = rows.map((r) => ({
    id: r.id,
    name: r.name,
    address: r.address,
    site_type: r.site_type,
    cpt_code: r.cpt_code,
    cash_price: r.cash_price,
    negotiated_rate: r.negotiated_rate,
    in_network_payers: r.in_network_payers,
    quality_score: r.quality_score,
    avg_wait_days: r.avg_wait_days,
    lat: r.lat,
    lng: r.lng,
  }));

  const { error } = await supabase.from("ins_shoppable_sites").upsert(payload, { onConflict: "id" });

  if (error) {
    console.error("Upsert failed:", error.message);
    process.exit(1);
  }

  console.log(`Upserted ${payload.length} shoppable site rows.`);
}

void main();
