/**
 * @file CopyableDocumentation.tsx
 * @description One-click copy and "Insert into Note" for clinical justification text.
 */

'use client';

import React, { useState, useCallback } from 'react';
import { Copy, Check, FileText } from 'lucide-react';
import type { MLPrediction } from '@/lib/cds-platform/ml/types';
import type { ClinicalScenario } from '@/lib/cds-platform/types';
import type { SHAPFeatureContribution } from '@/lib/cds-platform/ml/types';

export interface CopyableDocumentationProps {
  prediction: MLPrediction;
  scenario: ClinicalScenario;
  /** Callback when "Insert into Note" is clicked (SMART on FHIR write to EHR note). */
  onInsertIntoNote?: () => void;
  /** Optional ARIA label */
  'aria-label'?: string;
}

function scoreToRecommendation(score: number): string {
  if (score >= 7) return 'Appropriate for this indication.';
  if (score >= 4) return 'Consider discussing alternatives with the patient.';
  return 'Not recommended; consider alternative imaging or clinical management.';
}

function getTopFactors(prediction: MLPrediction, n: number): string[] {
  const contribs = prediction.shapValues?.featureContributions ?? [];
  return [...contribs]
    .sort((a, b) => Math.abs(b.shapValue) - Math.abs(a.shapValue))
    .slice(0, n)
    .map((c) => c.feature);
}

function buildDocumentationText(prediction: MLPrediction, scenario: ClinicalScenario): string {
  const score = Math.round(Math.max(1, Math.min(9, prediction.score)));
  const category = prediction.category ?? (score >= 7 ? 'Appropriate' : score >= 4 ? 'Uncertain' : 'Not Appropriate');
  const orderedStudy = [scenario.proposedImaging?.modality, scenario.proposedImaging?.bodyPart]
    .filter(Boolean)
    .join(' ') || 'Ordered study';
  const indication = scenario.proposedImaging?.indication ?? scenario.chiefComplaint ?? 'indication';
  const factors = getTopFactors(prediction, 5);
  const recommendation = scoreToRecommendation(score);

  return `Imaging appropriateness assessment performed. ${orderedStudy} for ${indication} scored ${score}/9 (${category}). Key factors: ${factors.join(', ')}. ${recommendation} Assessment generated by ARKA AIIE v2.0.`;
}

export function CopyableDocumentation({
  prediction,
  scenario,
  onInsertIntoNote,
  'aria-label': ariaLabel,
}: CopyableDocumentationProps) {
  const [copied, setCopied] = useState(false);
  const text = buildDocumentationText(prediction, scenario);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  }, [text]);

  return (
    <section
      className="flex flex-col gap-3 rounded-lg border border-[var(--arka-border,#e5e7eb)] bg-[var(--arka-bg-elevated,#fff)] p-3 dark:border-[var(--arka-border)] dark:bg-[var(--arka-bg-elevated)]"
      aria-label={ariaLabel ?? 'Clinical documentation for chart'}
    >
      <p className="text-xs text-[var(--arka-fg-muted,#6b7280)] dark:text-[var(--arka-fg-muted)]">
        Copy-paste ready text for the chart:
      </p>
      <blockquote
        className="rounded border border-[var(--arka-border,#e5e7eb)] bg-[var(--arka-bg-muted,#f9fafb)] px-3 py-2 text-[11px] leading-relaxed text-[var(--arka-fg,#111827)] dark:border-[var(--arka-border)] dark:bg-[var(--arka-bg-muted)] dark:text-[var(--arka-fg)]"
        cite="ARKA AIIE v2.0"
      >
        {text}
      </blockquote>
      <div className="flex flex-wrap gap-2">
        <button
          type="button"
          onClick={handleCopy}
          className="inline-flex items-center gap-2 rounded-md border border-[var(--arka-border,#e5e7eb)] bg-[var(--arka-bg,#fff)] px-3 py-1.5 text-xs font-medium text-[var(--arka-fg,#111827)] hover:bg-[var(--arka-bg-muted,#f3f4f6)] focus:outline-none focus:ring-2 focus:ring-[var(--arka-primary,#0ea5e9)] dark:border-[var(--arka-border)] dark:bg-[var(--arka-bg)] dark:text-[var(--arka-fg)] dark:hover:bg-[var(--arka-bg-muted)]"
          aria-label="Copy to clipboard"
        >
          {copied ? (
            <>
              <Check className="h-4 w-4 text-emerald-500" aria-hidden />
              Copied
            </>
          ) : (
            <>
              <Copy className="h-4 w-4" aria-hidden />
              Copy to Clipboard
            </>
          )}
        </button>
        {onInsertIntoNote && (
          <button
            type="button"
            onClick={onInsertIntoNote}
            className="inline-flex items-center gap-2 rounded-md bg-[var(--arka-primary,#0ea5e9)] px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 focus:outline-none focus:ring-2 focus:ring-[var(--arka-primary)] focus:ring-offset-2 dark:focus:ring-offset-[var(--arka-bg)]"
            aria-label="Insert into EHR note"
          >
            <FileText className="h-4 w-4" aria-hidden />
            Insert into Note
          </button>
        )}
      </div>
    </section>
  );
}
